version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:${PORT:-5000}"
    environment:
      PORT: ${PORT}
      DB_URI: mongodb://mongo:27017/neosante-pharmacy
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      BACK_END_URL: ${BACK_END_URL}
      FRONT_END_URL: ${FRONT_END_URL}
      FRONT_APP_PORT: ${FRONT_APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo-data: