name: Backend Tests and Docker Build

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      - name: Install dependencies
        working-directory: ./NeoSante-Pharmacy  # Specify correct path
        run: npm install --legacy-peer-deps

      - name: Run tests
        working-directory: ./NeoSante-Pharmacy  # Specify correct path
        run: npm run test

  build-and-push:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./NeoSante-Pharmacy  # Specify correct context
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:pr-${{ github.event.pull_request.number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}